const EN={home:'Home',quests:'Quests',map:'Map',profile:'Profile',nickname:'Nickname',save:'Save profile',language:'Language',photo:'Photo verification',mapTitle:'Busan Sea Quest Map',homeEyebrow:'WELCOME TO BUSAN',homeCta:'⚓ Start a quest',homeGuide:'Today’s sea adventure',photoTitle:'Verify with a photo',photoText:'Complete a mission at a Busan location.',mapGuideTitle:'Your sea map',mapGuideText:'Photos and memories collect on your map.',rewardTitle:'Busan local rewards',rewardText:'Unlock special rewards as you finish quests.',questDone:'Quest complete',current:'This quest is available now.',unlock:'Complete the previous quest to unlock.',complete:'Complete',location:'My location'};
function englishPlace(quest){return `Busan location ${quest.id}`}
function englishTitle(quest){return `Complete Busan Quest ${quest.id}`}
function localizeText(){const english=language==='en',set=(id,value)=>{const el=document.getElementById(id);if(el)el.textContent=value};if(english){set('homeNavLabel',EN.home);set('questsNavLabel',EN.quests);set('mapNavLabel',EN.map);set('profileNavLabel',EN.profile);set('profileLanguageLabel',EN.language);set('profilePhotoLabel','Change photo');set('saveProfileButton',EN.save);document.getElementById('rename').placeholder=EN.nickname;set('mapTitle',EN.mapTitle);set('locationButton',EN.location);set('completeLabel',EN.complete);set('availableGuide','Available');set('completeGuide','Complete');set('lockedGuide','Locked');set('homeEyebrow',EN.homeEyebrow);set('homeCta',EN.homeCta);set('homeGuideTitle',EN.homeGuide);set('guidePhotoTitle',EN.photoTitle);set('guidePhotoText',EN.photoText);set('guideMapTitle',EN.mapGuideTitle);set('guideMapText',EN.mapGuideText);set('guideRewardTitle',EN.rewardTitle);set('guideRewardText',EN.rewardText)}else{set('homeNavLabel','홈');set('profileLanguageLabel','언어 선택');set('homeEyebrow','WELCOME TO BUSAN');set('homeCta','⚓ 퀘스트 시작');set('homeGuideTitle','오늘의 바다 탐험');set('guidePhotoTitle','사진으로 인증');set('guidePhotoText','부산의 장소에서 미션을 완료해요.');set('guideMapTitle','나만의 바다 지도');set('guideMapText','찍은 사진과 추억이 지도에 쌓여요.');set('guideRewardTitle','부산 로컬 보상');set('guideRewardText','퀘스트 완료 후 특별한 보상을 만나요.')}}
function setProfileLanguage(nextLanguage){language=nextLanguage;localStorage.busanFeverLanguage=nextLanguage;render();localizeText();renderQuestPath();renderMapMarkers();updateHome()}
const baseRenderQuestPath=renderQuestPath;renderQuestPath=function(){baseRenderQuestPath();if(language!=='en')return;document.querySelectorAll('#questPath .path-quest').forEach((card,index)=>{const quest=QUESTS.find(item=>item.id===Number(card.querySelector('.quest-number').textContent));card.querySelector('.quest-label strong').textContent=englishPlace(quest);card.querySelector('.quest-label span').textContent=completedQuestIds.includes(quest.id)?EN.questDone:englishTitle(quest)});document.getElementById('sectionArea').textContent='Busan sea adventure route'};
const baseRenderMapMarkers=renderMapMarkers;renderMapMarkers=function(){baseRenderMapMarkers();if(language!=='en')return;questMarkerLayer.eachLayer(marker=>{const quest=QUESTS.find(item=>item.lat===marker.getLatLng().lat&&item.lng===marker.getLatLng().lng);if(!quest)return;const record=questRecords[quest.id];let html=`<div class="quest-popup"><strong>${quest.id}. ${englishPlace(quest)}</strong><span>${englishTitle(quest)}</span>`;if(record)html+=`<img src="${record.photo}" alt="${englishPlace(quest)}"><span>Completed: ${new Date(record.completedAt).toLocaleString('en-US')}</span><span>Reward: ${quest.reward}</span>`;else html+=`<span>${quest.id===getCurrentQuestId()?EN.current:EN.unlock}</span>`;marker.bindPopup(html+'</div>')})};
const baseUpdateHome=updateHome;updateHome=function(){baseUpdateHome();if(language==='en'){const name=localStorage.nickname||'Explorer',current=getCurrentQuestId();document.getElementById('homeGreeting').innerHTML=`${name},<br>let’s collect the sea!`;document.getElementById('homeStatus').textContent=current>55?'You completed all 55 Busan sea quests!':`Busan Quest ${current} is waiting for you.`}localizeText()};
const baseShowProfile=showProfile;showProfile=function(){baseShowProfile();localizeText()};
const originalSelectLanguage=selectLanguage;selectLanguage=function(nextLanguage){originalSelectLanguage(nextLanguage);localizeText()};
localizeText();
